"""+user.url_img

Revision ID: ae6273f6904a
Revises: b384873b8146
Create Date: 2021-09-18 20:05:24.683617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6273f6904a'
down_revision = 'b384873b8146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('game', 'release_date',
               # existing_type=sa.DATE(),
               # nullable=True)#
    # --- Unfortunately, SQLite not support "alter column" operation
    op.add_column('user', sa.Column('description', sa.String(), nullable=True))
    op.add_column('user', sa.Column('url_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'url_img')
    op.drop_column('user', 'description')
    op.alter_column('game', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
